//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TTS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กก,กก
        ///กกขนาก,กก-ขะ-หฺนาก
        ///กกช้าง,กก-ช้าง
        ///กกธูป,กก-ทูบ
        ///กกหู,กก-หู
        ///กกุธภัณฑ์,กะ-กุด-ทะ-พัน
        ///กง,กง
        ///กงกอน,กง-กอน
        ///กงการ,กง-กาน
        ///กงค้าง,กง-ค้าง
        ///กงจักร,กง-จัก
        ///กงฉาก,กง-ฉาก
        ///กงพัด,กง-พัด
        ///กงวาน,กง-วาน
        ///กงสี,กง-สี
        ///กงสุล,กง-สุน
        ///กงเกวียน,กง-เกฺวียน
        ///กงเกวียนกำเกวียน,กง-เกฺวียน-กัม-เกฺวียน
        ///กงเต๊ก,กง-เต๊ก
        ///กงโก้,กง-โก้
        ///กงไฉ่,กง-ฉั่ย
        ///กช,กด
        ///กชกร,กด-กอน
        ///กฎ,กด
        ///กฎกระทรวง,กด-กฺระ-ซวง
        ///กฎข้อบังคับ,กด-ค่อ-บัง-คับ
        ///กฎทบวง,กด-ทะ-บวง
        ///กฎธรรมชาติ,กด-ทัม-มะ-ชาด
        ///กฎธรรมดา,กด-ทัม-มะ-ดา
        ///กฎบัตร,กด-บัด
        ///กฎบัตรกฎหมาย,กด-บ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThaiWordDict {
            get {
                return ResourceManager.GetString("ThaiWordDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขก ขค ขฅ ขง ขจ ขฉ ขช ขญ ขฎ ขฏ ขฐ ขณ ขด ขต ขถ ขท ขธ ขน ขบ ขป ขผ ขฝ ขพ ขฟ ขภ ขม ขย ขร ขล ขว ขศ ขษ ขส ขห ขอ คก คข คฅ คง คจ คฉ คช คญ คฎ คฏ คฐ คณ คด คต คถ คท คธ คน คบ คป คผ คฝ คพ คฟ คภ คม คย คร คล คว คศ คษ คส คห คอ ฅก ฅข ฅค ฅง ฅจ ฅฉ ฅช ฅญ ฅฎ ฅฏ ฅฐ ฅณ ฅด ฅต ฅถ ฅท ฅธ ฅน ฅบ ฅป ฅผ ฅฝ ฅพ ฅฟ ฅภ ฅม ฅย ฅร ฅล ฅว ฅศ ฅษ ฅส ฅห ฅอ จก จข จค จฅ จง จฉ จช จญ จฎ จฏ จฐ จณ จด จต จถ จท จธ จน จบ จป จผ จฝ จพ จฟ จภ จม จย จร จล จว จศ จษ จส จห จอ ฉก ฉข ฉค ฉฅ ฉง ฉจ ฉช ฉญ ฉฎ ฉฏ ฉฐ ฉณ ฉด ฉต ฉถ ฉท ฉธ ฉน ฉบ ฉป ฉผ ฉฝ ฉพ ฉฟ ฉภ ฉม ฉย ฉร ฉล ฉว ฉศ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TwoConsDict {
            get {
                return ResourceManager.GetString("TwoConsDict", resourceCulture);
            }
        }
    }
}
